services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lfdb
      - SPRING_DATASOURCE_USERNAME=lotus
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_FLYWAY_ENABLED=true
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lfdb
      POSTGRES_USER: lotus
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
